apiVersion: apps/v1
kind: Deployment
metadata:
  name: day2-app-deployment
  labels:
    app: day2-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: day2-app
  template:
    metadata:
      labels:
        app: day2-app
    spec:
      containers:
        - name: day2-app
          image: rahulsharma9001/assignment-1:v1
          ports:
            - containerPort: 8080
          resources:
            requests:
              memory: "64Mi"
              cpu: "250m"
            limits:
              memory: "128Mi"
              cpu: "500m"
